#pragma once

#include <QHash>
#include <QSqlDatabase>
#include <QString>
#include <QVector>

namespace lexis {

// Unit-normalized dense word vector.
using EmbeddingVector = QVector<float>;

// Read-only access to the pre-computed word-embedding database
// (data/embeddings.db, generated by scripts/generate_embedding_db.py).
// All lookups gracefully return empty vectors when the database is absent,
// so callers can fall back to lexical heuristics.
class EmbeddingLookup {
 public:
  struct RankedWord {
    QString word;
    int rank = 0;
    EmbeddingVector vector;
  };

  static bool open(const QString& databasePath);
  static void close();
  static bool isOpen();
  static QString databasePath();

  static EmbeddingVector lookup(const QString& languageCode, const QString& word);
  // Most frequent vocabulary words, used as label candidates for new groups.
  static QVector<RankedWord> topWords(const QString& languageCode, int limit);

  static EmbeddingVector decodeVector(const QByteArray& blob);

 private:
  static QSqlDatabase connection();
};

}  // namespace lexis
